#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    stair_case = ""
    padding = n
    for num in range(n):
        stair_case = stair_case + "#"
        print(stair_case.rjust(padding," "))
        

if __name__ == '__main__':
    n = int(input())

    staircase(n)
